name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: lowlighter/metrics@v3.29
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_isocalendar: yes
