name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: "Activity"
        uses: lowlighter/metrics@v3.29
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: activity, metadata
          config_timezone: America/Chicago
          plugin_followup: true
          plugin_followup_sections: user
      - name: "Code Snippet"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: cpp, rust, typescript
          plugin_code_load: 400
