name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: lowlighter/metrics@v3.29
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: activity, metadata
          config_timezone: America/Chicago
          plugin_followup: true
          plugin_followup_sections: user
